
import { WeatherMoodEntry, Song, WeatherCondition, Mood } from '../types';

export const moodWeatherData: WeatherMoodEntry[] = [
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Rain","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Fog","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Fog","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Fog","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Rain","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Rain","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Rain","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Rain","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Fog","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Rain","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Happy","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Snow","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Fog","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Clear","mood_fitness":"Tired","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Clear","mood_fitness":"Neutral","mood_fitness_binary":"happy"},
  {"weather_conditions":"Fog","mood_fitness":"Stressed","mood_fitness_binary":"sad"},
  {"weather_conditions":"Snow","mood_fitness":"Happy","mood_fitness_binary":"happy"}
];

export const kpopMusicData: Song[] = [
  {"노래 제목":"좋은 날","가수":"아이유","mood_hits_en":"happy", "youtube_video_id": "jeqdYqsrsA0"},
  {"노래 제목":"밤편지","가수":"아이유","mood_hits_en":"sad", "youtube_video_id": "tqvu42S6e4g"},
  {"노래 제목":"Palette (팔레트)","가수":"아이유 (feat. G-DRAGON)","mood_hits_en":"happy", "youtube_video_id": "d9IxdwEFk1c"},
  {"노래 제목":"블루밍 (Blueming)","가수":"아이유","mood_hits_en":"happy", "youtube_video_id": "D1QQZ-Spm-A"},
  {"노래 제목":"Love wins all","가수":"아이유","mood_hits_en":"sad", "youtube_video_id": "JleoAppaxi0"},
  {"노래 제목":"에잇 (Eight)","가수":"아이유 (feat. SUGA)","mood_hits_en":"happy", "youtube_video_id": "TgOu00Mf3kI"},
  {"노래 제목":"Celebrity","가수":"아이유","mood_hits_en":"happy", "youtube_video_id": "0-q1KafFCLU"},
  {"노래 제목":"라일락","가수":"아이유","mood_hits_en":"happy", "youtube_video_id": "v7bnOxV4jAc"},
  {"노래 제목":"봄날","가수":"방탄소년단","mood_hits_en":"sad", "youtube_video_id": "xEeFrLSkMm8"},
  {"노래 제목":"작은 것들을 위한 시 (Boy With Luv)","가수":"방탄소년단 (feat. Halsey)","mood_hits_en":"happy", "youtube_video_id": "XsX3ATc3Auw"},
  {"노래 제목":"피 땀 눈물","가수":"방탄소년단","mood_hits_en":"sad", "youtube_video_id": "hmE9f-TEutc"},
  {"노래 제목":"Butterfly (Korean Ver.)","가수":"방탄소년단","mood_hits_en":"sad", "youtube_video_id": "Tf44oHIL-Sg"},
  {"노래 제목":"거짓말","가수":"빅뱅","mood_hits_en":"sad", "youtube_video_id": "2Cv3phvP8Ro"},
  {"노래 제목":"하루하루","가수":"빅뱅","mood_hits_en":"sad", "youtube_video_id": "MzCbEdtNbJ0"},
  {"노래 제목":"Fantastic Baby","가수":"빅뱅","mood_hits_en":"happy", "youtube_video_id": "AAbokV76tkU"},
  {"노래 제목":"에라 모르겠다 (FXXK IT)","가수":"빅뱅","mood_hits_en":"happy", "youtube_video_id": "iIPH89dhhqA"},
  {"노래 제목":"휘파람","가수":"BLACKPINK","mood_hits_en":"happy", "youtube_video_id": "dISNgvVpWlo"},
  {"노래 제목":"붐바야","가수":"BLACKPINK","mood_hits_en":"happy", "youtube_video_id": "bwmSjveL3Lc"},
  {"노래 제목":"마지막처럼","가수":"BLACKPINK","mood_hits_en":"happy", "youtube_video_id": "Amq-qlqbjYA"},
  {"노래 제목":"뚜두뚜두 (DDU-DU DDU-DU)","가수":"BLACKPINK","mood_hits_en":"happy", "youtube_video_id": "IHNzOHi8sJs"},
  {"노래 제목":"CHEER UP","가수":"TWICE","mood_hits_en":"happy", "youtube_video_id": "c7rCyll5AeY"},
  {"노래 제목":"TT","가수":"TWICE","mood_hits_en":"happy", "youtube_video_id": "ePpPVE-GGJw"},
  {"노래 제목":"LIKEY","가수":"TWICE","mood_hits_en":"happy", "youtube_video_id": "V2hlQkVJZhE"},
  {"노래 제목":"FANCY","가수":"TWICE","mood_hits_en":"happy", "youtube_video_id": "kOHB85vDuow"},
  {"노래 제목":"으르렁 (Growl)","가수":"EXO","mood_hits_en":"happy", "youtube_video_id": "I3dezFzsNss"},
  {"노래 제목":"중독 (Overdose)","가수":"EXO","mood_hits_en":"happy", "youtube_video_id": "TI0DGvqKZTI"},
  {"노래 제목":"Love Shot","가수":"EXO","mood_hits_en":"happy", "youtube_video_id": "pSudEWBAYRE"},
  {"노래 제목":"빨간 맛 (Red Flavor)","가수":"Red Velvet","mood_hits_en":"happy", "youtube_video_id": "WyiIGEHQP8o"},
  {"노래 제목":"Bad Boy","가수":"Red Velvet","mood_hits_en":"sad", "youtube_video_id": "J_CFBjAyPWE"},
  {"노래 제목":"Psycho","가수":"Red Velvet","mood_hits_en":"sad", "youtube_video_id": "uR8Mrt1IpXg"},
  {"노래 제목":"Hype Boy","가수":"NewJeans","mood_hits_en":"happy", "youtube_video_id": "11cta61wi0g"},
  {"노래 제목":"Ditto","가수":"NewJeans","mood_hits_en":"sad", "youtube_video_id": "pSUydWEqKwE"},
  {"노래 제목":"Attention","가수":"NewJeans","mood_hits_en":"happy", "youtube_video_id": "js1CtxSY38I"},
  {"노래 제목":"아주 NICE","가수":"SEVENTEEN","mood_hits_en":"happy", "youtube_video_id": "J-wFp43XOrA"},
  {"노래 제목":"손오공 (Super)","가수":"SEVENTEEN","mood_hits_en":"happy", "youtube_video_id": "Gy_ka0bA9e8"},
  {"노래 제목":"HOT","가수":"SEVENTEEN","mood_hits_en":"happy", "youtube_video_id": "-GQg25oP0S4"},
  {"노래 제목":"TOMBOY","가수":"(G)I-DLE","mood_hits_en":"happy", "youtube_video_id": "Jh4QFaPmdss"},
  {"노래 제목":"퀸카 (Queencard)","가수":"(G)I-DLE","mood_hits_en":"happy", "youtube_video_id": "7HDeem-JaSY"},
  {"노래 제목":"LOVE DIVE","가수":"IVE","mood_hits_en":"happy", "youtube_video_id": "Y8JFxS1HlDo"},
  {"노래 제목":"I AM","가수":"IVE","mood_hits_en":"happy", "youtube_video_id": "6ZUIwj3FgUY"},
  {"노래 제목":"ELEVEN","가수":"IVE","mood_hits_en":"happy", "youtube_video_id": "-odp21tDN_0"},
  {"노래 제목":"ANTIFRAGILE","가수":"LE SSERAFIM","mood_hits_en":"happy", "youtube_video_id": "pyf8cbqyfPs"},
  {"노래 제목":"UNFORGIVEN (Korean Ver.)","가수":"LE SSERAFIM","mood_hits_en":"happy", "youtube_video_id": "fzS_YhC83oQ"},
  {"노래 제목":"Next Level","가수":"aespa","mood_hits_en":"happy", "youtube_video_id": "4TWR90KJl84"},
  {"노래 제목":"Savage","가수":"aespa","mood_hits_en":"happy", "youtube_video_id": "WPdWvnAAurg"},
  {"노래 제목":"Spicy","가수":"aespa","mood_hits_en":"happy", "youtube_video_id": "Os_heh8vPfs"},
  {"노래 제목":"Gee","가수":"소녀시대","mood_hits_en":"happy", "youtube_video_id": "U7mPqycQ0tQ"},
  {"노래 제목":"소원을 말해봐 (Genie)","가수":"소녀시대","mood_hits_en":"happy", "youtube_video_id": "6SwiSpudKWI"},
  {"노래 제목":"다시 만난 세계","가수":"소녀시대","mood_hits_en":"happy", "youtube_video_id": "0k2Zzkw_-0I"},
  {"노래 제목":"내가 제일 잘 나가","가수":"2NE1","mood_hits_en":"happy", "youtube_video_id": "j7_lSP8Vc3o"},
  {"노래 제목":"Lonely","가수":"2NE1","mood_hits_en":"sad", "youtube_video_id": "5n4V3lGEyG4"},
  {"노래 제목":"그리워해요","가수":"2NE1","mood_hits_en":"sad", "youtube_video_id": "AG0jlKdB1s0"},
  {"노래 제목":"Tell Me","가수":"원더걸스","mood_hits_en":"happy", "youtube_video_id": "bl6Q7khtvg8"},
  {"노래 제목":"Nobody (Korean Ver.)","가수":"원더걸스","mood_hits_en":"happy", "youtube_video_id": "QZBn1e9pr24"},
  {"노래 제목":"강남스타일","가수":"싸이","mood_hits_en":"happy", "youtube_video_id": "9bZkp7q19f0"},
  {"노래 제목":"That That (prod. & feat. SUGA of BTS)","가수":"싸이","mood_hits_en":"happy", "youtube_video_id": "8dJyRm2jJ-U"},
  {"노래 제목":"아무노래","가수":"지코","mood_hits_en":"happy", "youtube_video_id": "UuV2BmJ1p_I"},
  {"노래 제목":"사람","가수":"지코","mood_hits_en":"sad", "youtube_video_id": "1n-pj0k-t-M"},
  {"노래 제목":"200%","가수":"AKMU","mood_hits_en":"happy", "youtube_video_id": "0Oi8jDMvd_w"},
  {"노래 제목":"Give Love","가수":"AKMU","mood_hits_en":"happy", "youtube_video_id": "x2XX3cNW4K0"},
  {"노래 제목":"시간과 낙엽","가수":"AKMU","mood_hits_en":"sad", "youtube_video_id": "s2_gS0L-zI8"},
  {"노래 제목":"우주를 줄게","가수":"볼빨간사춘기","mood_hits_en":"happy", "youtube_video_id": "9U8uA702xrE"},
  {"노래 제목":"나만, 봄","가수":"볼빨간사춘기","mood_hits_en":"happy", "youtube_video_id": "p2O41gS_i2s"},
  {"노래 제목":"벚꽃 엔딩","가수":"버스커 버스커","mood_hits_en":"happy", "youtube_video_id": "tXV7dfvSefo"},
  {"노래 제목":"여수 밤바다","가수":"버스커 버스커","mood_hits_en":"happy", "youtube_video_id": "k3_KP6yUWEQ"},
  {"노래 제목":"스토커","가수":"10cm","mood_hits_en":"sad", "youtube_video_id": "k3_KP6yUWEQ"},
  {"노래 제목":"폰서트","가수":"10cm","mood_hits_en":"happy", "youtube_video_id": "Wyse-t_Lw2w"},
  {"노래 제목":"모든 날, 모든 순간","가수":"폴킴","mood_hits_en":"sad", "youtube_video_id": "Y0s_t0_isS4"},
  {"노래 제목":"너를 만나","가수":"폴킴","mood_hits_en":"happy", "youtube_video_id":"o_wn292_Nso"},
  {"노래 제목":"선물","가수":"멜로망스","mood_hits_en":"happy", "youtube_video_id":"q2f5b8VPAJk"},
  {"노래 제목":"Love, Maybe (사내맞선 OST)","가수":"멜로망스","mood_hits_en":"happy", "youtube_video_id":"4h5BMAl8rGM"},
  {"노래 제목":"비도 오고 그래서 (feat. 신용재)","가수":"헤이즈","mood_hits_en":"sad", "youtube_video_id":"afxLaQiLu-o"},
  {"노래 제목":"널 너무 모르고","가수":"헤이즈","mood_hits_en":"sad", "youtube_video_id":"vvkWaI91_eU"},
  {"노래 제목":"가끔","가수":"크러쉬","mood_hits_en":"sad", "youtube_video_id":"2go3L9sde_k"},
  {"노래 제목":"NAPPA","가수":"크러쉬","mood_hits_en":"happy", "youtube_video_id":"T1k54d8Al2g"},
  {"노래 제목":"우산 (feat. 윤하)","가수":"에픽하이","mood_hits_en":"sad", "youtube_video_id":"NIPtyAKylI4"},
  {"노래 제목":"Love Love Love (feat. 박봄)","가수":"에픽하이","mood_hits_en":"happy", "youtube_video_id":"vTryPDD-kI8"},
  {"노래 제목":"불꽃놀이 (feat. Sumi Jo)","가수":"다이나믹 듀오","mood_hits_en":"happy", "youtube_video_id":"yP1QBUQj4cE"},
  {"노래 제목":"시간이 흐른 뒤","가수":"윤미래","mood_hits_en":"sad", "youtube_video_id":"PgngB0I_uVI"},
  {"노래 제목":"총맞은 것처럼","가수":"백지영","mood_hits_en":"sad", "youtube_video_id":"4BF9aHYh1W4"},
  {"노래 제목":"8282","가수":"다비치","mood_hits_en":"happy", "youtube_video_id":"pIu8hGWEjA0"},
  {"노래 제목":"또 운다 또","가수":"다비치","mood_hits_en":"sad", "youtube_video_id":"eBHzd2bxs54"},
  {"노래 제목":"가시","가수":"버즈","mood_hits_en":"sad", "youtube_video_id":"s0smb5t2Ejo"},
  {"노래 제목":"겁쟁이","가수":"버즈","mood_hits_en":"sad", "youtube_video_id":"hB-qiCxHA_E"},
  {"노래 제목":"라라라","가수":"SG워너비","mood_hits_en":"happy", "youtube_video_id":"zYDjz6m0v7g"},
  {"노래 제목":"살다가","가수":"브라운 아이드 소울","mood_hits_en":"sad", "youtube_video_id":"yFfM6d-8O4M"},
  {"노래 제목":"바람기억","가수":"나얼","mood_hits_en":"sad", "youtube_video_id":"D_jG4v7lBw0"},
  {"노래 제목":"보고싶다","가수":"김범수","mood_hits_en":"sad", "youtube_video_id":"PY7eG-A_v4k"},
  {"노래 제목":"야생화","가수":"박효신","mood_hits_en":"sad", "youtube_video_id":"OxgiiyL-huY"},
  {"노래 제목":"Timeless","가수":"SG워너비","mood_hits_en":"sad", "youtube_video_id":"AYe5UjfgRFA"},
  {"노래 제목":"죄와 벌","가수":"SG워너비","mood_hits_en":"sad", "youtube_video_id":"x-G2b_SHvrM"},
  {"노래 제목":"이러지마 제발","가수":"케이윌","mood_hits_en":"sad", "youtube_video_id":"DoxU0fk6dbs"},
  {"노래 제목":"촌스럽게 왜 그래","가수":"케이윌","mood_hits_en":"happy", "youtube_video_id":"alZ9hG0-aY4"},
  {"노래 제목":"Ring Ding Dong","가수":"SHINee","mood_hits_en":"happy", "youtube_video_id":"roughtzsCDI"},
  {"노래 제목":"Sherlock•셜록","가수":"SHINee","mood_hits_en":"happy", "youtube_video_id":"8kyG5tTZ1iE"},
  {"노래 제목":"Electric Shock","가수":"f(x)","mood_hits_en":"happy", "youtube_video_id":"n8I8QGFA1oM"},
  {"노래 제목":"Hot Summer","가수":"f(x)","mood_hits_en":"happy", "youtube_video_id":"z-rftpZ7f_s"},
  {"노래 제목":"Roly-Poly","가수":"T-ARA","mood_hits_en":"happy", "youtube_video_id":"afwK0J3sR_4"},
  {"노래 제목":"Lovey-Dovey","가수":"T-ARA","mood_hits_en":"happy", "youtube_video_id":"CJ0djllyqwY"},
  {"노래 제목":"Touch My Body","가수":"SISTAR","mood_hits_en":"happy", "youtube_video_id":"Q33SoblaZbU"}
];

export const getWeatherMoodMap = (): Map<WeatherCondition, Mood> => {
  const weatherMoodMap = new Map<WeatherCondition, Mood>();
  weatherMoodMap.set('Clear', 'happy');
  weatherMoodMap.set('Snow', 'happy');
  weatherMoodMap.set('Fog', 'sad');
  weatherMoodMap.set('Rain', 'sad');
  return weatherMoodMap;
};

export const getSongsByMood = (songs: Song[], mood: Mood): Song[] => {
  return songs.filter(song => song.mood_hits_en === mood);
};